### ISSUE TITLE
What is the value of the insert size ?

### ISSUE THREAD

**Issue by Taalouane** [brentp/goleft#70]
Hi @brentp,

I am interested in evaluating the coverage and insert-size of my BAM files (Human WGS).
I used the covstats function and would like to know what the value is for the insert-size from the results I got below?
```

coverage        insert_mean     insert_sd       insert_5th      insert_95th     template_mean   template_sd     pct_unmapped    pct_bad_reads   pct_duplicate   pct_proper_pair read_length     bam     sample
35.45   81.32   86.95   -53     234     376.85  83.96   0.02    7.8     7.8     91.2    151     SampleA.bam  SampleA
```

Note: with qualimap, I found an "insert-size" of 366 (but in terms of execution time it is longer compared to goleft that's why I switched to goleft)

Thank you in advance for your response !!
Tarek

**Comment by brentp** [comment]
So "insert-size" is actually the inside measurement and fragment length is the outside measurement.

So qualimap is reporting fragment length of 366 and indexstats is reporting 376.86.

Note that from goleft, insert_mean=86.96 and template_mean=376.86 which makes sense since your reads are about 150 bases each so we expect about 300 bases difference. (template_mean == fragment_length).

**Comment by Taalouane** [comment]
Thank you for your quick reply !!

So I think you define insert_mean as Inner-distance?
To my knowledge insert-size also includes the size of reads as described here https://www.biostars.org/p/95803/ 

Tarek
